"""Backend-neutral persistence for the three relational tables.

Why this layer exists: the error catalog, the audit trail, and the escalation
queue were SQLite rows in a file under `data/`. That is the right default on a
laptop and in CI — no server, no credentials, no fixtures, and `pytest` starts
cold in milliseconds — and it is the wrong thing on ECS Fargate, where several
tasks serve the same escalation queue and a file in a container's writable layer
is neither shared between them nor durable across a redeploy.

The interface is deliberately narrow. It exposes the dozen operations
`knowledge/catalog.py` actually performs rather than a general query API,
because a general API would leak dialect differences back out to every caller,
which is the thing this layer exists to contain.

The two backends share their SQL, because the schema is plain enough to be
portable. They differ only where the dialects genuinely differ:

- **Placeholders.** `sqlite3` is `qmark` (`?`), `psycopg` is `pyformat` (`%s`).
  Statements are written once with `?` and rewritten for Postgres. That rewrite
  is a blunt `str.replace`, which is safe *only* because no statement here
  contains a literal `?` or `%`; both would need escaping. Anything added below
  must keep that true.
- **Generated keys.** `INTEGER PRIMARY KEY AUTOINCREMENT` against
  `GENERATED BY DEFAULT AS IDENTITY`, and `cursor.lastrowid` against
  `RETURNING id`.
- **Timestamps.** Both store ISO-8601 UTC *text*, not a native timestamp type.
  `TIMESTAMPTZ` would be the better Postgres column — it is smaller, indexes
  better, and validates. It is not used because it comes back as a `datetime`
  rather than a string, and every existing consumer (`/metrics` slices
  `created_at[:10]`, the Streamlit console parses it with pandas, the tests
  compare strings) would have to change to a shape that then differs by
  backend. Storing text keeps one row shape for both. It costs correct type
  checking at the column level and a few bytes per row; ordering is unaffected
  because ISO-8601 UTC with a `Z` suffix sorts lexicographically exactly as it
  sorts chronologically.

Connections are opened per operation on both backends. For SQLite that is
free. For Postgres it is a handshake per query, which is the honest cost of not
carrying a pool: at this system's write rate — one audit row per answered
question — it does not register, and `psycopg_pool` is the obvious change if
that stops being true.
"""

from __future__ import annotations

import json
from abc import ABC, abstractmethod
from collections.abc import Iterator, Sequence
from contextlib import contextmanager
from typing import Any

from aiops.schemas import ErrorCodeEntry

# Column lists live here rather than being inlined per statement so that the
# INSERT, the SELECT, and the two schemas cannot drift apart silently.
ERROR_CODE_COLUMNS = (
    "code",
    "service",
    "title",
    "severity",
    "description",
    "likely_causes",
    "remediation",
    "runbook_ref",
)

AUDIT_COLUMNS = (
    "created_at",
    "trace_id",
    "question",
    "route",
    "verdict",
    "confidence",
    "answer",
    "citations",
    "guardrails",
    "latency_ms",
    "cost_usd",
    "input_tokens",
    "output_tokens",
)

ESCALATION_COLUMNS = (
    "created_at",
    "audit_id",
    "question",
    "draft",
    "reason",
    "confidence",
)


class StorageBackend(ABC):
    """The three tables, as operations rather than as SQL.

    Subclasses supply a cursor, a schema, a row adapter, and a way to recover a
    generated primary key. Everything else is shared.
    """

    #: DB-API paramstyle marker used to rewrite the shared statements.
    placeholder: str = "?"
    #: Appended to INSERTs on backends that cannot report `lastrowid`.
    returning_clause: str = ""

    def __init__(self) -> None:
        # Schema creation is idempotent but not free, and the previous code ran
        # it at the top of five different public functions. On SQLite that was
        # invisible; on Postgres a `CREATE TABLE IF NOT EXISTS` per audit write
        # takes a lock in every transaction. Tracking which targets have been
        # prepared makes it once per target per process instead.
        #
        # It is a set rather than a bool because the SQLite backend resolves its
        # path lazily from settings, and the tests point it at a fresh tmp file
        # mid-run — a single flag would skip the DDL on the new file.
        self._prepared: set[str] = set()

    # -- subclass contract -------------------------------------------------

    @abstractmethod
    @contextmanager
    def _cursor(self) -> Iterator[Any]:
        """Yield a DB-API cursor, committing on clean exit and rolling back otherwise."""
        raise NotImplementedError

    @property
    @abstractmethod
    def _schema_statements(self) -> tuple[str, ...]:
        """DDL for this dialect, as individually executable statements."""
        raise NotImplementedError

    @property
    @abstractmethod
    def _target(self) -> str:
        """Stable identity of what this backend writes to, for the prepared-set."""
        raise NotImplementedError

    @abstractmethod
    def _rows(self, cursor: Any) -> list[dict[str, Any]]:
        """Drain a cursor into plain dicts. Both backends must agree on key names."""
        raise NotImplementedError

    @abstractmethod
    def _generated_id(self, cursor: Any) -> int:
        """Primary key of the row the cursor just inserted."""
        raise NotImplementedError

    # -- statement helpers -------------------------------------------------

    def _sql(self, statement: str) -> str:
        if self.placeholder == "?":
            return statement
        return statement.replace("?", self.placeholder)

    def _marks(self, n: int) -> str:
        return ",".join(self.placeholder for _ in range(n))

    # -- schema ------------------------------------------------------------

    def ensure_schema(self, force: bool = False) -> None:
        """Create the tables if they are missing. Cheap to call; runs once per target."""
        target = self._target
        if not force and target in self._prepared:
            return
        with self._cursor() as cur:
            for statement in self._schema_statements:
                cur.execute(statement)
        self._prepared.add(target)

    # -- error codes -------------------------------------------------------

    def upsert_error_codes(self, entries: Sequence[ErrorCodeEntry]) -> int:
        """Insert-or-replace the catalog. Returns the number of rows written.

        Upsert rather than truncate-and-load: seeding runs on every API and UI
        start, and dropping the table first would make the catalog briefly empty
        for any task already serving traffic.
        """
        self.ensure_schema()
        columns = ", ".join(ERROR_CODE_COLUMNS)
        updates = ", ".join(f"{c}=excluded.{c}" for c in ERROR_CODE_COLUMNS if c != "code")
        sql = self._sql(
            f"INSERT INTO error_codes ({columns}) VALUES ({self._marks(len(ERROR_CODE_COLUMNS))}) "
            f"ON CONFLICT (code) DO UPDATE SET {updates}"
        )
        with self._cursor() as cur:
            for e in entries:
                cur.execute(
                    sql,
                    (
                        e.code,
                        e.service,
                        e.title,
                        e.severity,
                        e.description,
                        # Stored as a JSON string in both backends. Postgres has
                        # JSONB and it would be the better column, but the value
                        # is only ever read whole and never queried into, so the
                        # gain is nil and the cost is a row shape that differs
                        # by backend.
                        json.dumps(e.likely_causes),
                        e.remediation,
                        e.runbook_ref,
                    ),
                )
        return len(entries)

    def fetch_error_code(self, code: str) -> dict[str, Any] | None:
        self.ensure_schema()
        with self._cursor() as cur:
            cur.execute(self._sql("SELECT * FROM error_codes WHERE code = ?"), (code,))
            rows = self._rows(cur)
        return rows[0] if rows else None

    def fetch_error_codes(self, codes: Sequence[str]) -> list[dict[str, Any]]:
        if not codes:
            return []
        self.ensure_schema()
        with self._cursor() as cur:
            cur.execute(
                f"SELECT * FROM error_codes WHERE code IN ({self._marks(len(codes))})",
                tuple(codes),
            )
            return self._rows(cur)

    def fetch_error_codes_for_service(self, service: str) -> list[dict[str, Any]]:
        self.ensure_schema()
        with self._cursor() as cur:
            cur.execute(self._sql("SELECT * FROM error_codes WHERE service = ?"), (service,))
            return self._rows(cur)

    def fetch_all_error_codes(self) -> list[dict[str, Any]]:
        self.ensure_schema()
        with self._cursor() as cur:
            cur.execute("SELECT * FROM error_codes ORDER BY code")
            return self._rows(cur)

    # -- audit -------------------------------------------------------------

    def insert_audit(self, record: dict[str, Any]) -> int:
        """Persist one answer. `record` must carry every key in AUDIT_COLUMNS."""
        self.ensure_schema()
        columns = ", ".join(AUDIT_COLUMNS)
        sql = self._sql(
            f"INSERT INTO query_audit ({columns}) VALUES ({self._marks(len(AUDIT_COLUMNS))})"
            f"{self.returning_clause}"
        )
        with self._cursor() as cur:
            cur.execute(sql, tuple(record[c] for c in AUDIT_COLUMNS))
            return self._generated_id(cur)

    def fetch_audit(self, limit: int) -> list[dict[str, Any]]:
        self.ensure_schema()
        with self._cursor() as cur:
            cur.execute(
                self._sql("SELECT * FROM query_audit ORDER BY created_at DESC, id DESC LIMIT ?"),
                (limit,),
            )
            return self._rows(cur)

    # -- escalations -------------------------------------------------------

    def insert_escalation(self, record: dict[str, Any]) -> int:
        self.ensure_schema()
        columns = ", ".join(ESCALATION_COLUMNS)
        sql = self._sql(
            f"INSERT INTO escalations ({columns}) VALUES ({self._marks(len(ESCALATION_COLUMNS))})"
            f"{self.returning_clause}"
        )
        with self._cursor() as cur:
            cur.execute(sql, tuple(record[c] for c in ESCALATION_COLUMNS))
            return self._generated_id(cur)

    def fetch_escalations(self, status: str | None, limit: int) -> list[dict[str, Any]]:
        self.ensure_schema()
        with self._cursor() as cur:
            if status:
                cur.execute(
                    self._sql(
                        "SELECT * FROM escalations WHERE status = ? "
                        "ORDER BY created_at DESC, id DESC LIMIT ?"
                    ),
                    (status, limit),
                )
            else:
                cur.execute(
                    self._sql("SELECT * FROM escalations ORDER BY created_at DESC, id DESC LIMIT ?"),
                    (limit,),
                )
            return self._rows(cur)

    def update_escalation(
        self, escalation_id: int, status: str, reviewer: str, resolution: str, resolved_at: str
    ) -> None:
        self.ensure_schema()
        with self._cursor() as cur:
            cur.execute(
                self._sql(
                    "UPDATE escalations SET status=?, reviewer=?, resolution=?, resolved_at=? WHERE id=?"
                ),
                (status, reviewer, resolution, resolved_at, escalation_id),
            )


class MissingDependency(RuntimeError):
    """A backend was selected whose driver is not installed.

    Raised with the extra to install rather than letting an `ImportError` from
    three frames down reach the operator, because "no module named psycopg" does
    not tell anyone that `AIOPS_DB_URL` is what asked for it.
    """
