"""PostgreSQL backend, selected by setting `AIOPS_DB_URL`.

This exists for one reason: on ECS Fargate the escalation queue is shared state.
Several tasks answer questions, any of them can queue an escalation, and the
on-call engineer who approves one is talking to whichever task the load balancer
picked. A SQLite file in a task's writable layer gives each task a private
queue and loses all of them on redeploy, which is not a smaller version of the
right behaviour — it is the wrong behaviour.

**psycopg 3, not SQLAlchemy.** The queries here are eleven hand-written
statements over three tables with no relationships to map and no dynamic query
construction. An ORM or even Core would add a dependency and an abstraction
whose value is portability the raw statements already have, since the SQL is
plain enough that the dialect gap is placeholders, identity columns, and
`lastrowid` — all of which are handled in `base.py` in under twenty lines.
SQLAlchemy earns its place when queries are composed at runtime; these are not.

`psycopg` is an **optional** dependency (`pip install ".[postgres]"`) and is
imported inside the connect path, so a machine without it behaves exactly as
before as long as `AIOPS_DB_URL` is unset. Selecting this backend without the
driver raises `MissingDependency` naming the extra, rather than an ImportError
from three frames down that says nothing about which setting asked for it.

Types differ from the SQLite schema in two places worth stating:

- `DOUBLE PRECISION`, not `REAL`. SQLite's `REAL` is an 8-byte IEEE double;
  Postgres's `REAL` is 4-byte. Using `REAL` here would silently round every
  confidence and cost figure to ~7 significant digits — small, but a difference
  in stored values between backends is exactly the kind of thing that makes a
  cross-backend comparison untrustworthy later.
- `GENERATED BY DEFAULT AS IDENTITY`, not `SERIAL`. `SERIAL` is the legacy
  spelling: it creates a separately-owned sequence that survives some `ALTER`
  paths and confuses `pg_dump` round-trips. Identity columns are the SQL
  standard and PG 10+ default.
"""

from __future__ import annotations

from collections.abc import Iterator
from contextlib import contextmanager
from typing import Any

from aiops.storage.base import MissingDependency, StorageBackend

SCHEMA_STATEMENTS: tuple[str, ...] = (
    """
    CREATE TABLE IF NOT EXISTS error_codes (
        code           TEXT PRIMARY KEY,
        service        TEXT NOT NULL,
        title          TEXT NOT NULL,
        severity       TEXT NOT NULL,
        description    TEXT NOT NULL,
        likely_causes  TEXT NOT NULL,   -- JSON array, stored as text: see base.py
        remediation    TEXT NOT NULL,
        runbook_ref    TEXT
    )
    """,
    "CREATE INDEX IF NOT EXISTS idx_error_codes_service ON error_codes(service)",
    """
    CREATE TABLE IF NOT EXISTS query_audit (
        id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        created_at    TEXT NOT NULL,
        trace_id      TEXT,
        question      TEXT NOT NULL,
        route         TEXT,
        verdict       TEXT NOT NULL,
        confidence    DOUBLE PRECISION NOT NULL,
        answer        TEXT,
        citations     TEXT,
        guardrails    TEXT,
        latency_ms    BIGINT,
        cost_usd      DOUBLE PRECISION,
        input_tokens  BIGINT DEFAULT 0,
        output_tokens BIGINT DEFAULT 0
    )
    """,
    "CREATE INDEX IF NOT EXISTS idx_audit_created ON query_audit(created_at)",
    "CREATE INDEX IF NOT EXISTS idx_audit_verdict ON query_audit(verdict)",
    """
    CREATE TABLE IF NOT EXISTS escalations (
        id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        created_at  TEXT NOT NULL,
        audit_id    BIGINT,
        question    TEXT NOT NULL,
        draft       TEXT,
        reason      TEXT NOT NULL,
        confidence  DOUBLE PRECISION NOT NULL,
        status      TEXT NOT NULL DEFAULT 'pending',
        reviewer    TEXT,
        resolution  TEXT,
        resolved_at TEXT,
        FOREIGN KEY (audit_id) REFERENCES query_audit(id)
    )
    """,
    "CREATE INDEX IF NOT EXISTS idx_escalations_status ON escalations(status)",
)


def normalise_dsn(url: str) -> str:
    """Strip a SQLAlchemy-style `+driver` suffix from the scheme.

    libpq accepts `postgresql://` and `postgres://` and nothing else, but
    `postgresql+psycopg://` is what anyone who has used SQLAlchemy will type,
    and the failure it produces ("invalid URI scheme") does not suggest the fix.
    """
    scheme, sep, rest = url.partition("://")
    if not sep:
        return url
    base = scheme.split("+", 1)[0]
    return f"{base}{sep}{rest}"


def is_postgres_url(url: str | None) -> bool:
    if not url:
        return False
    scheme = url.partition("://")[0].split("+", 1)[0].lower()
    return scheme in {"postgres", "postgresql"}


class PostgresBackend(StorageBackend):
    """Shared relational storage for multi-task deployments."""

    placeholder = "%s"
    # psycopg has no lastrowid, and would not want one — RETURNING is the
    # correct way to recover a generated key and is atomic with the insert.
    returning_clause = " RETURNING id"

    def __init__(self, url: str) -> None:
        super().__init__()
        self.url = normalise_dsn(url)

    @property
    def _target(self) -> str:
        return self.url

    @property
    def _schema_statements(self) -> tuple[str, ...]:
        return SCHEMA_STATEMENTS

    @contextmanager
    def _cursor(self) -> Iterator[Any]:
        psycopg, dict_row = _import_psycopg()
        conn = psycopg.connect(self.url, row_factory=dict_row)
        try:
            with conn.cursor() as cur:
                yield cur
            conn.commit()
        except BaseException:
            conn.rollback()
            raise
        finally:
            conn.close()

    def _rows(self, cursor: Any) -> list[dict[str, Any]]:
        # dict_row already produces dicts; the copy keeps the return type a
        # plain list[dict] regardless of what psycopg hands back.
        return [dict(r) for r in cursor.fetchall()]

    def _generated_id(self, cursor: Any) -> int:
        row = cursor.fetchone()
        return int(row["id"]) if row else 0

    def __repr__(self) -> str:
        # Never interpolate self.url — it usually carries a password.
        host = self.url.rpartition("@")[2] or "?"
        return f"PostgresBackend({host})"


def _import_psycopg() -> tuple[Any, Any]:
    try:
        import psycopg
        from psycopg.rows import dict_row
    except ImportError as exc:  # pragma: no cover - exercised via monkeypatch
        raise MissingDependency(
            "AIOPS_DB_URL points at PostgreSQL but the psycopg driver is not installed. "
            'Install it with: pip install "aiops-copilot[postgres]"'
        ) from exc
    return psycopg, dict_row
